### ISSUE TITLE
[Error 111]connection refused error

### ISSUE THREAD

**Issue by hitdezhazha** [alphaville/optimization-engine#278]
I try to call the opengen MPC algorithm to calculate at a constant frequency(for now 25Hz), but every time after servel seconds there comes this error: [Error 111]connection refused.
![image](https://user-images.githubusercontent.com/39644572/180715254-1016be1f-206e-4164-9672-03e01e8b1d9f.png)

**Comment by alphaville** [comment]
Could you please provide some additional information? Does the server work and then it fails, or does it never connect?

**Comment by alphaville** [comment]
Most likely, this is because you are trying to connect to a server that doesn't bind to the address you have provided. This is a safety precaution: when you design your TCP interface, you need to provide an IP. If the IP you used there is not `192.168.137.1`, the server will not accept requests. You can allow incoming requests at all IPs by using the address `0.0.0.0`. However, without looking at your code I cannot tell what the issue might be. I will close this issue for now, but feel free to comment.
